delivey_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

# from payment.views import payment_process
from user.views import login_user, user_logout, login_admin, home, dashboard, sample, settings_data, become_partner, \
    banner_data, send_email, send_sms, tnc, partner_tnc, driver_tnc, privacy_policy, help_view, subscribe

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_admin),
    path('send_sms/', send_sms),
    path('x/', sample),
    path('tnc/', tnc),
    path('partner_tnc/', partner_tnc),
    path('driver_tnc/', driver_tnc),
    # path('payment_process/', payment_process),
    path('banner_data/', banner_data),
    path('privacy_policy/', privacy_policy),
    path('help/', help_view),
    path('subscribe/', subscribe),
    path('logout/', user_logout),
    path('home/', dashboard),
    path('settings/', settings_data),
    path('become_partner/', become_partner),
    path('user/', include('user.urls')),
    path('category/', include('category.urls')),
    path('payment/', include('payment.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user.views import *

urlpatterns = [
    path('login/', login_user),
    path('login_with_password/', login_with_password),
    path('logout/', user_logout),
    path('otp_verify/', otp_verify),
    path('forgot_password/', forgot_password),
    path('resend_otp/', resend_otp),
    path('change_password/', change_password),
    path('delete/', delete),
    path('home/', home),
    path('search_vendor/', search_vendor),
    path('edit_avatar/', edit_avatar),
    path('user_profile/', user_profile),
    path('reset_password/', reset_password),
    path('user_list/', user_data),

    path('vendor_list/', vendor_data),
    path('add_vendor/', add_vendor),
    path('edit_vendor/<int:vendor_id>/', edit_vendor),
    path('view_vendor/<int:vendor_id>/', view_vendor),
    path('add_subcategory/<int:vendor_id>/', add_subcategory_vendor),
    path('vendors/', vendor_data_mobile),
    path('pending_orders/', pending_orders),
    path('vendors/<int:vendor_id>/orders/', vendor_orders),
    path('vendor/<int:vendor_id>/offers/', vendor_offer_mobile),
    path('offer_delete/', vendor_offer_delete),
    path('vendor/<int:vendor_id>/', vendor_details),
    # path('offers/<int:vendor_id>/', vendor_offer_for_user),

    path('view_executive/<int:executive_id>/', view_executive),
    path('executive/<int:executive_id>/', executive_details),

    path('option_list/', option_data),


    path('executive_list/', executive_data),
    path('add_executive/', add_executive),
    path('edit_executive/<int:executive_id>/', edit_executive),

    path('orders/', order_data),
    path('address_list/', address_data),

    path('cancel_order/<int:order_id>/', cancel_order),
    path('order/<int:order_id>/', order_details_mobile),

    path('executive/<int:executive_id>/orders/', executive_orders),
    path('executive/<int:executive_id>/status/', executive_status),

    path('admin_user_list/', admin_user_list),
    path('edit_admin_user/', edit_admin_user),
    path('user_exists/', user_exists),
    path('admin_change_password/', admin_change_password),

    path('change_category_status/', change_category_status),
    path('change_sub_category_status/', change_sub_category_status),
    path('change_user_status/', change_user_status),

    path('<int:vendor_id>/vendor_report/', vendor_report),
    path('<int:vendor_id>/vendor_report_download/', vendor_report_download),
    path('<int:executive_id>/executive_report/', executive_report),
    path('<int:executive_id>/executive_report_download/', executive_report_download),

    path('send_report/', send_report),


]

category/models.py
from django.db import models

# Create your models here.
# from payment.models import Invoice
from delivey_app.managres import LocationManager
from payment.models import Invoice
from user.models import VendorData, User, ExecutiveData

STATUS = ((1, 'Created'),
          (2, 'Accepted'),
          (3, 'Rejected'),
          (4, 'In-Progress'),
          (5, 'Picked Up'),
          (6, 'Delivered'),
          (7, 'Cancelled'),
          (8, 'Ready To Dispatch'),
          )

PAYMENT_STATUS = ((1, 'Pending'),
                  (2, 'Success'),
                  (3, 'Failed'))

PAYOUT_STATUS = ((1, 'Pending'),
                  (2, 'Cancelled'),
                  (3, 'Complete'),
                  (4, 'Under Review'))


class SettingData(models.Model):
    key = models.CharField(max_length=250)
    value = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.key


class CategoryData(models.Model):
    name = models.CharField(max_length=250)
    is_active = models.BooleanField(default=True)
    image = models.ImageField(upload_to='', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.name


class SubCategoryData(models.Model):
    category = models.ForeignKey(CategoryData, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=250)
    is_active = models.BooleanField(default=True)
    image = models.ImageField(upload_to='', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.name


class VendorSubCategoryData(models.Model):
    sub_category = models.ForeignKey(SubCategoryData, on_delete=models.CASCADE, null=True, blank=True)
    vendor = models.ForeignKey(VendorData, on_delete=models.CASCADE, null=True, blank=True)
    price = models.CharField(max_length=255, default=0, null=True, blank=True)
    offer_price = models.CharField(max_length=255, default=0, null=True, blank=True)
    quantity = models.CharField(max_length=255, default=0, null=True, blank=True)
    unit = models.CharField(max_length=50, default='kg')
    is_available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.sub_category.name


class VendorOfferData(models.Model):
    vendor = models.ForeignKey(VendorData, on_delete=models.CASCADE, null=True, blank=True)
    code = models.CharField(max_length=255, null=True, blank=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    percentage = models.CharField(max_length=255, default=0, null=True, blank=True)
    start = models.DateField(null=True, blank=True)
    end = models.DateField(null=True, blank=True)
    is_available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.vendor.shop_name


class OrderData(models.Model):
    invoice = models.ForeignKey(
        Invoice,
        null=True,
        blank=True,
        on_delete=models.DO_NOTHING,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        related_name='user')

    objects = LocationManager()
    status = models.PositiveIntegerField(choices=STATUS, default=1)
    vendor = models.ForeignKey(VendorData, null=True, on_delete=models.CASCADE, blank=True)
    delivery_boy = models.ForeignKey(ExecutiveData, on_delete=models.SET_NULL, null=True, related_name='delivery_boy')
    is_home_delivery = models.BooleanField(default=True)
    delivery_image = models.ImageField(upload_to='', null=True, blank=True)
    booking_slot = models.TextField(default='', blank=True)

    title = models.TextField(max_length=500, null=True)
    drop_address = models.TextField(max_length=500, null=True)
    drop_latitude = models.DecimalField(max_digits=9, decimal_places=7, blank=True, null=True)
    drop_longitude = models.DecimalField(max_digits=9, decimal_places=7, blank=True, null=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=7, blank=True, null=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=7, blank=True, null=True)
    notes = models.TextField(max_length=1000, null=True, blank=True)
    custom_id = models.TextField(null=True, blank=True)
    offer_id = models.CharField(max_length=100, default=0,null=True, blank=True)

    tip = models.CharField(max_length=100, default=0, null=True, blank=True)

    discount = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    supplier_fee = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    packing_charge = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    mile_charge = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    driver_charge = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    tax = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    total = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    total_bill = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    skype_amount = models.CharField(max_length=100, default=0, null=True, blank=True)
    sub_total_1 = models.CharField(max_length=100, default=0, null=True, blank=True)
    service_fee_deducted = models.DecimalField(max_digits=7, decimal_places=2, default=0, null=True, blank=True)
    delivery_charge_deducted = models.DecimalField(max_digits=7, decimal_places=2, default=0, null=True, blank=True)
    customer_transaction_value = models.CharField(max_length=100, default=0, null=True, blank=True)
    meat4all_platform_fee_20_percent = models.CharField(max_length=100, default=0, null=True, blank=True)
    sub_total_2 = models.CharField(max_length=100, default=0, null=True, blank=True)
    stripe_payout_charge_vendor = models.DecimalField(max_digits=7, decimal_places=2, default=0, null=True, blank=True)
    vendor_payout = models.DecimalField(max_digits=7, decimal_places=2, default=0, null=True, blank=True)
    stripe_payout_charge_driver = models.DecimalField(max_digits=7, decimal_places=2, default=0, null=True, blank=True)
    driver_payout = models.DecimalField(max_digits=7, decimal_places=2, default=0, null=True, blank=True)
    platform_fee_driver = models.DecimalField(max_digits=7, decimal_places=2, default=0, null=True, blank=True)
    total_m4a_amount = models.CharField(max_length=100, default=0, null=True, blank=True)
    net_value_m4a = models.CharField(max_length=100, default=0, null=True, blank=True)

    meat4all_amount = models.CharField(max_length=100, default=0, null=True, blank=True)
    # meat4all_amount_per = models.CharField(max_length=100, default=0, null=True, blank=True)
    vendor_amount = models.CharField(max_length=100, default=0, null=True, blank=True)
    vendor_amount_per = models.CharField(max_length=100, default=0, null=True, blank=True)
    driver_amount_per = models.CharField(max_length=100, default=0, null=True, blank=True)
    driver_amount = models.CharField(max_length=100, default=0, null=True, blank=True)

    meat4all_driver_amount = models.CharField(max_length=100, default=0, null=True, blank=True)

    stripe_payment_id = models.CharField(max_length=250, null=True, blank=True)
    firebase_key = models.CharField(max_length=100, null=True, blank=True)
    cancel_reason = models.TextField(max_length=1000, null=True, blank=True)
    executive_rating = models.PositiveSmallIntegerField(null=True, blank=True)
    executive_feedback = models.TextField(max_length=1000, null=True, blank=True)
    vendor_rating = models.PositiveSmallIntegerField(null=True, blank=True)
    vendor_feedback = models.TextField(max_length=1000, null=True, blank=True)
    assigned_executive = models.BooleanField(default=False)
    payment_status = models.PositiveIntegerField(choices=PAYMENT_STATUS, default=1)
    payout_status = models.PositiveIntegerField(choices=PAYOUT_STATUS, default=1)
    driver_payout_status = models.PositiveIntegerField(choices=PAYOUT_STATUS, default=1)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    order_date = models.DateField(null=True)

    def __str__(self):
        return "%s" % self.id


class PaymentHistoryData(models.Model):

    objects = LocationManager()
    payout_reference = models.TextField(null=True, blank=True)
    contact_id = models.TextField(null=True, blank=True)
    total_amount = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    contact_email = models.TextField(null=True, blank=True)
    contact_name = models.TextField(null=True, blank=True)
    contact_phone_number = models.TextField(null=True, blank=True)
    payout_date = models.TextField(null=True, blank=True)
    payout_type = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return "%s" % self.id



class OrderServices(models.Model):
    service = models.ForeignKey(
        VendorSubCategoryData,
        null=True,
        on_delete=models.DO_NOTHING,
    )

    order = models.ForeignKey(
        OrderData,
        null=True,
        on_delete=models.DO_NOTHING)

    quantity = models.CharField(max_length=30, null=True)
    note = models.TextField(default='', blank=True)
    price = models.CharField(max_length=30, null=True)
    unit = models.CharField(max_length=30, null=True)
    is_removed = models.BooleanField(default=False)

    def __str__(self):

templates/payout/order_details.html
{% extends 'base.html' %}
{% load static %}
{% block meta_block %}
{% endblock %}
{% block css %}

{% endblock %}


{% block main_content %}
    <div class="row form-group">
        <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
            <h4><a href="/category/order_list/"><i class="text-danger fas fa-arrow-alt-circle-left"></i></a> {{ order_obj.custom_id }}</h4>
        </div>
        <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">
            {#             <a class="btn btn-rounded btn-primary btn-sm waves-effect float-right" href="/user/add_order/">#}
            {#                Add#}
            {#            </a>#}
        </div>
    </div>

    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="row margin-top">
            <div class="col-lg-6 col-md-6 display-flex">
                <div class="card width-100">
                    <div class="d-flex p-3 align-items-center bg-info backgound-table-color">
                        <h5 class="card-title mb-0 text-uppercase">Basic Details</h5>
                    </div>
                    <div class="card-body">
                        <div>
                            <table class="table text-muted mb-0 no-wrap recent-table font-light" style="text-align: left!important;">
                                <tbody style="text-align: left!important;">
                                <tr>
                                    <td class="txt-oflo">ID</td>
                                    <td class="txt-oflo bold-font">{{ order_obj.id }}</td>
                                </tr>
                                <tr>
                                    <td class="txt-oflo">Date</td>
                                    <td class="txt-oflo bold-font">{{ order_obj.created }}</td>
                                </tr>
                                <tr>
                                    <td class="txt-oflo">User</td>
                                    <td class="txt-oflo bold-font">{{ order_obj.user.first_name }} {{ order_obj.user.last_name }}</td>
                                </tr>
                                <tr>
                                    <td class="txt-oflo">Vendor</td>
                                    <td class="txt-oflo bold-font">{{ order_obj.vendor.shop_name }}</td>
                                </tr>
{#                                <tr>#}
{#                                    <td class="txt-oflo">Vendor Amount</td>#}
{#                                    <td class="txt-oflo bold-font">{{ vendor_amount }}</td>#}
{#                                </tr>#}
{#                                <tr>#}
{#                                    <td class="txt-oflo">Meat4All Amount</td>#}
{#                                    <td class="txt-oflo bold-font">{{ meat4all_amount }}</td>#}
{#                                </tr>#}
                                <tr>
                                    <td class="txt-oflo">Drop Address</td>
                                    <td class="txt-oflo bold-font">{{ order_obj.drop_address }}</td>
                                </tr>
                                <tr>
                                    <td class="txt-oflo">Status</td>
                                    <td class="txt-oflo bold-font">{{ order_obj.get_status_display }}</td>
                                </tr>
                                {% if order_obj.status == 6 %}
                                    <tr>
                                        <td class="txt-oflo">Delivery Image</td>
                                        <td class="txt-oflo bold-font">
                                            <a target="_blank" href="{{ base_image_url }}/media/{{ order_obj.delivery_image }}">
                                                <img style="height: 30px" src="{{ base_image_url }}/media/{{ order_obj.delivery_image }}">
                                            </a>
                                        </td>
                                    </tr>
                                {% endif %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-6 display-flex">
                <div class="card width-100">
                    <div class="d-flex p-3 align-items-center bg-info backgound-table-color">
                        <h5 class="card-title mb-0 text-uppercase">Services</h5>
                    </div>
                    <div class="card-body">
                        <div>
                            <table class="table text-muted mb-0 no-wrap recent-table font-light" style="text-align: left!important;">
                                <tbody style="text-align: left!important;">
                                <tr>
                                    <th>Name</th>
                                    <th>Quantity</th>
                                    <th>Price</th>
                                    <th>Unit</th>
                                    <th>Removed</th>
                                </tr>
                                {% for obj in order_obj.orderservices_set.all %}
                                    <tr>
                                        <td class="txt-oflo">{{ obj.service.sub_category.name }}</td>
                                        <td class="txt-oflo bold-font">{{ obj.quantity }}</td>
                                        <td class="txt-oflo bold-font">£ {{ obj.price }}</td>
                                        <td class="txt-oflo bold-font">{{ obj.unit }}</td>
                                        <td class="txt-oflo bold-font">{% if obj.is_removed %} Yes {% else %}No {% endif %}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="row margin-top">
            <div class="col-lg-6 col-md-6 display-flex">
                <div class="card width-100">
                    <div class="d-flex p-3 align-items-center bg-info backgound-table-color">
                        <h5 class="card-title mb-0 text-uppercase">Invoice</h5>
                    </div>
                    <div class="card-body">
                        <div>
                            <table class="table text-muted mb-0 no-wrap recent-table font-light" style="text-align: left!important;">
                                <tbody style="text-align: left!important;">
                                <tr>
                                    <td class="txt-oflo">Sub Total</td>
                                    <td class="txt-oflo">£ {{ order_obj.total }}</td>
                                </tr>

                                <tr>
                                    <td class="txt-oflo">Packing Charge</td>
                                    <td class="txt-oflo">£ {{ order_obj.packing_charge }}</td>
                                </tr>
                                <tr>
                                    <td class="txt-oflo">Delivery Charge</td>
                                    <td class="txt-oflo">£ {{ order_obj.mile_charge }}</td>
                                </tr>
                                <tr>
                                    <td class="txt-oflo">Discount (-)</td>
                                    <td class="txt-oflo">£ {{ order_obj.discount }}</td>
                                </tr>
                                <tr>
                                    <td class="txt-oflo">Total Bill</td>
                                    <td class="txt-oflo">£ {{ order_obj.total_bill }}</td>
                                </tr>


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-6 display-flex">
                <div class="card width-100">
                    <div class="d-flex p-3 align-items-center bg-info backgound-table-color">
                        <h5 class="card-title mb-0 text-uppercase">Transaction</h5>
                    </div>
                    <div class="card-body">
                        <div>
                            <table class="table text-muted mb-0 no-wrap recent-table font-light" style="text-align: left!important;">
                                <tbody style="text-align: left!important;">
                                 <tr>
                                    <td class="txt-oflo">Stripe Payment ID</td>
                                    <td class="txt-oflo">{{ order_obj.stripe_payment_id }}</td>
                                </tr>
                                <tr>
                                    <td class="txt-oflo">Payment Status</td>
                                    <td class="txt-oflo">{{ order_obj.get_payment_status_display }}</td>
                                </tr>

                                <tr>
                                    <td class="txt-oflo">M4A Percentage from Partner</td>
                                    <td class="txt-oflo">£ {{ order_obj.meat4all_amount }} ({{ order_obj.vendor_amount_per }} %)</td>
                                </tr>
                                <tr>
                                    <td class="txt-oflo">Vendor Amount</td>
                                    <td class="txt-oflo">£ {{ order_obj.vendor_amount }}</td>
                                </tr>
                                 <tr>
                                    <td class="txt-oflo">M4A Percentage from Driver</td>
                                    <td class="txt-oflo">£ {{ order_obj.meat4all_driver_amount }} ({{ order_obj.driver_amount_per }} %)</td>
                                </tr>
                                 <tr>
                                    <td class="txt-oflo">Driver Amount</td>
                                    <td class="txt-oflo">£ {{ order_obj.driver_amount }}</td>
                                </tr>



                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>


{% endblock %}
{% block js %}
{% endblock %}