delivey_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

# from payment.views import payment_process
from user.views import login_user, user_logout, login_admin, home, dashboard, sample, settings_data, become_partner, \
    banner_data, send_email, send_sms, tnc, partner_tnc, driver_tnc, privacy_policy, help_view, subscribe

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_admin),
    path('send_sms/', send_sms),
    path('x/', sample),
    path('tnc/', tnc),
    path('partner_tnc/', partner_tnc),
    path('driver_tnc/', driver_tnc),
    # path('payment_process/', payment_process),
    path('banner_data/', banner_data),
    path('privacy_policy/', privacy_policy),
    path('help/', help_view),
    path('subscribe/', subscribe),
    path('logout/', user_logout),
    path('home/', dashboard),
    path('settings/', settings_data),
    path('become_partner/', become_partner),
    path('user/', include('user.urls')),
    path('category/', include('category.urls')),
    path('payment/', include('payment.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user.views import *

urlpatterns = [
    path('login/', login_user),
    path('login_with_password/', login_with_password),
    path('logout/', user_logout),
    path('otp_verify/', otp_verify),
    path('forgot_password/', forgot_password),
    path('resend_otp/', resend_otp),
    path('change_password/', change_password),
    path('delete/', delete),
    path('home/', home),
    path('search_vendor/', search_vendor),
    path('edit_avatar/', edit_avatar),
    path('user_profile/', user_profile),
    path('reset_password/', reset_password),
    path('user_list/', user_data),

    path('vendor_list/', vendor_data),
    path('add_vendor/', add_vendor),
    path('edit_vendor/<int:vendor_id>/', edit_vendor),
    path('view_vendor/<int:vendor_id>/', view_vendor),
    path('add_subcategory/<int:vendor_id>/', add_subcategory_vendor),
    path('vendors/', vendor_data_mobile),
    path('pending_orders/', pending_orders),
    path('vendors/<int:vendor_id>/orders/', vendor_orders),
    path('vendor/<int:vendor_id>/offers/', vendor_offer_mobile),
    path('offer_delete/', vendor_offer_delete),
    path('vendor/<int:vendor_id>/', vendor_details),
    # path('offers/<int:vendor_id>/', vendor_offer_for_user),

    path('view_executive/<int:executive_id>/', view_executive),
    path('executive/<int:executive_id>/', executive_details),

    path('option_list/', option_data),


    path('executive_list/', executive_data),
    path('add_executive/', add_executive),
    path('edit_executive/<int:executive_id>/', edit_executive),

    path('orders/', order_data),
    path('address_list/', address_data),

    path('cancel_order/<int:order_id>/', cancel_order),
    path('order/<int:order_id>/', order_details_mobile),

    path('executive/<int:executive_id>/orders/', executive_orders),
    path('executive/<int:executive_id>/status/', executive_status),

    path('admin_user_list/', admin_user_list),
    path('edit_admin_user/', edit_admin_user),
    path('user_exists/', user_exists),
    path('admin_change_password/', admin_change_password),

    path('change_category_status/', change_category_status),
    path('change_sub_category_status/', change_sub_category_status),
    path('change_user_status/', change_user_status),

    path('<int:vendor_id>/vendor_report/', vendor_report),
    path('<int:vendor_id>/vendor_report_download/', vendor_report_download),
    path('<int:executive_id>/executive_report/', executive_report),
    path('<int:executive_id>/executive_report_download/', executive_report_download),

    path('send_report/', send_report),


]

user/models.py
import uuid

from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.db import models
from django.utils.crypto import get_random_string

from delivey_app.managres import LocationManager


def random_string():
    return uuid.uuid4().hex[:8]


class User(AbstractUser):
    isMobileVerified = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    is_email = models.BooleanField(default=True, null=True, blank=True)
    is_vendor = models.BooleanField(default=False)
    is_executive = models.BooleanField(default=False)
    is_user = models.BooleanField(default=False)
    is_profile_completed = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to='', null=True, blank=True)
    gcm_token = models.TextField(null=True)
    gender = models.CharField(max_length=20, null=True, blank=True)
    source = models.CharField(max_length=10, null=True)
    latitude = models.CharField(max_length=100, null=True)
    longitude = models.CharField(max_length=100, null=True)
    device_type = models.CharField(max_length=32, null=True, blank=True)
    stripe_customer_id = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.username


class AdminUserData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_category_access = models.BooleanField(default=False)
    is_sub_category_access = models.BooleanField(default=False)
    is_user_access = models.BooleanField(default=False)
    is_vendor_access = models.BooleanField(default=False)
    is_executive_access = models.BooleanField(default=False)
    is_option_access = models.BooleanField(default=False)
    is_order_access = models.BooleanField(default=False)
    is_admin_user_access = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    modified = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return "%s" % self.user.username


class AddressData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    block = models.CharField(max_length=100, null=True, blank=True)
    title = models.CharField(max_length=100, null=True, blank=True)
    landmark = models.CharField(max_length=100, null=True, blank=True)
    latitude = models.CharField(max_length=100, null=True, blank=True)
    longitude = models.CharField(max_length=100, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.user.username


class OtpData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    code = models.PositiveIntegerField(default=123123)
    isVerified = models.BooleanField(default=False)

    def __str__(self):
        return "%s" % self.user.username


class OptionData(models.Model):
    name = models.CharField(max_length=200)
    upto_3_mile = models.CharField(max_length=50, default=0, blank=True)
    from_3to5_mile = models.CharField(max_length=50, default=0, blank=True)
    from_5to10_mile = models.CharField(max_length=50, default=0, blank=True)
    from_10to30_mile = models.CharField(max_length=50, default=0, blank=True)
    driver_charge_upto_3_mile = models.CharField(max_length=50, default=0, blank=True)
    driver_charge_from_3to5_mile = models.CharField(max_length=50, default=0, blank=True)
    driver_charge_from_5to10_mile = models.CharField(max_length=50, default=0, blank=True)
    driver_charge_from_10to30_mile = models.CharField(max_length=50, default=0, blank=True)
    packing_charge = models.CharField(max_length=50, default=0, blank=True)
    supplier_fee = models.CharField(max_length=50, default=0, blank=True)
    vat = models.CharField(max_length=50, default=0, blank=True)
    cancel_charge = models.CharField(max_length=50, default=0, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.name


PAYMENT = (
    (1, 'Daily'),
    (2, 'Monthly'),
    (3, 'Weekly')
)


class VendorData(models.Model):
    objects = LocationManager()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    option = models.ForeignKey(OptionData, on_delete=models.CASCADE, null=True, blank=True)
    payment = models.PositiveIntegerField(choices=PAYMENT, default=3)
    shop_name = models.CharField(max_length=250, blank=True)
    email = models.EmailField(max_length=250, blank=True)
    mobile = models.CharField(max_length=50, blank=True)
    mobile2 = models.CharField(max_length=50, blank=True)
    latitude = models.CharField(max_length=100, null=True)
    longitude = models.CharField(max_length=100, null=True)
    rating = models.PositiveIntegerField(default=5)
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    city = models.CharField(max_length=250, null=True)
    pincode = models.CharField(max_length=50, null=True)
    address = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=False)
    meat4all_per = models.CharField(max_length=100, null=True)
    logo = models.ImageField(upload_to='', null=True, blank=True)
    bank_name = models.CharField(max_length=200, null=True, blank=True)
    sort_code = models.CharField(max_length=200, null=True, blank=True)
    account_no = models.CharField(max_length=200, null=True, blank=True)
    holder_name = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    balance = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return "%s" % self.shop_name


class VendorCertificateData(models.Model):
    vendor = models.ForeignKey(VendorData, on_delete=models.CASCADE, null=True, blank=True)
    file = models.FileField(upload_to='', null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    start = models.DateField(null=True, blank=True)
    end = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.vendor


class VendorImageData(models.Model):
    vendor = models.ForeignKey(VendorData, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to='', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.vendor


class ExecutiveData(models.Model):
    MODE = ((1, 'Motor Bike'),
              (2, 'Car'),
              (3, 'Bicycle'),
              )

    objects = LocationManager()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    mode = models.PositiveIntegerField(choices=MODE, default=1)
    payment = models.PositiveIntegerField(choices=PAYMENT, default=3)
    mobile = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=250, blank=True)
    mobile2 = models.CharField(max_length=50, blank=True)
    latitude = models.CharField(max_length=100, null=True)
    longitude = models.CharField(max_length=100, null=True)
    rating = models.PositiveIntegerField(default=5)
    city = models.CharField(max_length=250, null=True)
    de_charge_per = models.CharField(max_length=10, null=True)
    pincode = models.CharField(max_length=50, null=True)
    address = models.TextField(blank=True, null=True)
    v_name = models.CharField(max_length=100, null=True, blank=True)
    rc = models.FileField(upload_to='', null=True, blank=True)
    bank_name = models.CharField(max_length=200, null=True, blank=True)
    sort_code = models.CharField(max_length=200, null=True, blank=True)
    account_no = models.CharField(max_length=200, null=True, blank=True)
    holder_name = models.CharField(max_length=200, null=True, blank=True)

    dl_no = models.CharField(max_length=100, null=True, blank=True)
    dl_upload = models.FileField(upload_to='', null=True, blank=True)
    dl_date = models.DateField(null=True, blank=True)

    insurance = models.CharField(max_length=100, null=True, blank=True)
    insurance_upload = models.FileField(upload_to='', null=True, blank=True)

    is_verified = models.BooleanField(default=False)
    is_available = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    balance = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return "%s" % self.user


class ChargeSettingData(models.Model):
    # delivery_charge = models.CharField(max_length=50, default=0, blank=True)
    upto_3_mile = models.CharField(max_length=50, default=0, blank=True)
    from_3to5_mile = models.CharField(max_length=50, default=0, blank=True)
    from_5to10_mile = models.CharField(max_length=50, default=0, blank=True)
    from_10to30_mile = models.CharField(max_length=50, default=0, blank=True)
    driver_charge_upto_3_mile = models.CharField(max_length=50, default=0, blank=True)
    driver_charge_from_3to5_mile = models.CharField(max_length=50, default=0, blank=True)
    driver_charge_from_5to10_mile = models.CharField(max_length=50, default=0, blank=True)
    driver_charge_from_10to30_mile = models.CharField(max_length=50, default=0, blank=True)
    packing_charge_per = models.CharField(max_length=50, default=0, blank=True)

templates/executive/executive_list.html
{% extends 'base.html' %}
{% load static %}
{% block meta_block %}
{% endblock %}
{% block css %}

{% endblock %}


{% block main_content %}
    <div class="row form-group">
        <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
            <h4>Drivers</h4>
        </div>
        <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">
            <a class="btn btn-rounded btn-primary btn-sm waves-effect float-right" href="/user/add_executive/">
                Add
            </a>
        </div>
    </div>


    <div class="row form-group">
        <div class="col-sm-12">
            <div class="material-card card">
                <div class="card-body">
                    <div class="table-responsive scrollable scrollable" style="overflow: visible!important;">
                        <table id="zero_config" class="table text-muted mb-0 no-wrap recent-table font-light">
                            <thead>
                            <tr class="text-uppercase">
                                <th>#</th>
                                <th>Name</th>
                                <th>Mobile</th>
                                <th>Mode</th>
                                <th>Balance</th>
                                <th>Image</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for obj in executive_list %}
                                <tr>
                                    <td class="txt-oflo">{{ forloop.counter}}</td>
                                    <td class="txt-oflo">{{ obj.user.first_name }}</td>
                                    <td class="txt-oflo">{{ obj.user.username }}</td>
                                   
                                    <td class="txt-oflo">{{ obj.get_mode_display }}</td>
                                    <td class="txt-oflo">{{ obj.balance }}</td>
                                    <td class="txt-oflo">
                                        <a href="#">
                                            {% if obj.avatar == '' %}
                                                <img src="/static/img/avatar.png" style="height: 30px;">
                                            {% else %}
                                                <img src="{{ base_image_url }}/media/{{ obj.user.avatar }}" style="height: 30px;">
                                            {% endif %}
                                        </a>
                                    </td>
                                    <td class="txt-oflo"><a href="#!">{% if obj.is_verified %} Verified {% else %} Un-Verified {% endif %}</a></td>

                                    <td>
                                        <a class="btn btn-rounded btn-outline-danger btn-sm waves-effect" href="/user/edit_executive/{{ obj.id }}/?tab=6"><i class="fas fa fa-pencil-alt"></i></a>
                                        <a class="btn btn-rounded btn-outline-danger btn-sm waves-effect" href="/user/view_executive/{{ obj.id }}/?tab=6" ><i class="fas fa fa-eye"></i></a>
                                        <a class="btn btn-rounded btn-outline-danger btn-sm waves-effect" href="/user/{{ obj.id }}/executive_report/?tab=6" ><i class="fas fa fa-chart-area"></i></a>
                                    </td>

                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if executive_list.has_other_pages %}
        <ul class="pagination float-right" style="margin-bottom: 6%">
            {% if executive_list.has_previous %}
                <li class="margin-top" ><a href="?page={{ executive_list.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled margin-top"><span>&laquo;</span></li>
            {% endif %}
            {% for i in executive_list.paginator.page_range %}
                {% if executive_list.number == i %}
                    <li class="btn btn-primary m-1 active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a class="btn btn-secondary m-1" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if executive_list.has_next %}
                <li class="margin-top" ><a href="?page={{ executive_list.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled margin-top"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}
{% block js %}
{% endblock %}

templates/executive/profile.html
{% extends 'base.html' %}
{% load static %}
{% block meta_block %}
{% endblock %}
{% block css %}

{% endblock %}


{% block main_content %}
    <div class="row form-group">
        <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
            <h4><a href="/user/executive_list/"><i class="text-danger fas fa-arrow-alt-circle-left"></i></a> {{ executive_obj.user.first_name }}</h4>
        </div>
        <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">
            <a class="btn btn-rounded btn-primary btn-sm waves-effect float-right" href="/user/edit_executive/{{ executive_obj.id }}/">
                 <i class="fas fa fa-pencil-alt"></i>
            </a>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-lg-6">
            <div class="card">
                <div class="d-flex align-items-center p-3 bg-info backgound-table-color">
                    <h6 class="card-title white-text mb-0 text-uppercase">Basic Details</h6>
                </div>
                <div class="col-lg-12 col-md-12 col-xl-12 active collapse show" id="appraisals" data-parent="#accordion">
                    <div id="appraisal-questions">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <tbody>

                                    <tr>
                                        <th scope="row">Person Name:</th>
                                        <td>{{ executive_obj.user.first_name }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Username:</th>
                                        <td>{{ executive_obj.user.username }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Email:</th>
                                        <td>{{ executive_obj.email }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Contact Number:</th>
                                        <td>{{ executive_obj.mobile2 }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Transport Mode:</th>
                                        <td>{{ executive_obj.get_mode_display }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Address:</th>
                                        <td>{{ executive_obj.address }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Bank Name:</th>
                                        <td>{{ executive_obj.bank_name }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Sort Code:</th>
                                        <td>{{ executive_obj.sort_code }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Account Number:</th>
                                        <td>{{ executive_obj.account_no }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Ac Holder Name:</th>
                                        <td>{{ executive_obj.holder_name }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Payment:</th>
                                        <td>{{ executive_obj.get_payment_display }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Image:</th>
                                        <td>
                                               <a target="_blank" href="{{ base_image_url }}/media/{{ executive_obj.user.avatar  }}">
                                            <img style="height: 30px" src="{{ base_image_url }}/media/{{ executive_obj.user.avatar }}">
                                        </a>
                                        </td>
                                    </tr>

                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card">
                <div class="d-flex align-items-center p-3 bg-info backgound-table-color">
                    <h6 class="card-title white-text mb-0 text-uppercase">Other Details</h6>
                </div>
                <div class="col-lg-12 col-md-12 col-xl-12 active collapse show" id="appraisals" data-parent="#accordion">
                    <div id="appraisal-questions">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <th scope="row">Vehicle Number:</th>
                                        <td>{{ executive_obj.v_name }}</td>
                                    </tr>

                                    <tr>
                                        <th scope="row">DL Number:</th>
                                        <td>{{ executive_obj.dl_no }} ({{ executive_obj.dl_date }})</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">DL Upload:</th>
                                        <td><a href="{{ base_image_url }}/media/{{ executive_obj.dl_upload }}" target="_blank">
                                            <img style="height: 30px" src="{{ base_image_url }}/media/{{ executive_obj.dl_upload }}">
                                        </a></td>
                                    </tr>

                                    <tr>
                                        <th scope="row">Vehicle Registration Upload:</th>
                                        <td><a href="{{ base_image_url }}/media/{{ executive_obj.rc }}" target="_blank">
                                            <img style="height: 30px" src="{{ base_image_url }}/media/{{ executive_obj.rc }}">
                                        </a></td>
                                    </tr>

                                    <tr>
                                        <th scope="row">Insurance Valid:</th>
                                        <td>{{ executive_obj.insurance }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Insurance Upload:</th>
                                        <td><a href="{{ base_image_url }}/media/{{ executive_obj.insurance_upload }}" target="_blank">
                                            <img style="height: 30px" src="{{ base_image_url }}/media/{{ executive_obj.insurance_upload }}">
                                        </a></td>
                                    </tr>


                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
    </div>

{% endblock %}
{% block js %}
{% endblock %}